### ISSUE TITLE
Not supporting sub-collection of native types

### ISSUE THREAD

**Issue by macinnir** [macinnir/swagger-gen#6]
Every time a property is found, it is identified as being a native type, a reference to a definition, or an array of objects (definitions). There is currently no support for an array of native types (e.g. string).

This wouldn't work (currently): 
```
Pet:
    type: "object"
    properties:
      photoUrls:
        type: "array"
        items:
          type: "string"
```
